<div class="klearMatrixDashboard">

<h1 class="ui-state-active  ui-corner-all">${title}</h1>

{{each(idx,section) sections}}
<fieldset class="ui-widget-content ui-corner-all">
<legend class="ui-state-active  ui-corner-all">${section.name}</legend>
    <ul>
        {{each(idx2,subsection) section.subsects}}
        <li>
{{if (subsection.file)}}
            <a class="subsection" href="?" id="target-${subsection.file}" >
{{/if}}
{{if (subsection.class)}}
            <span class="ui-silk inline ${subsection.class}"></span>
{{/if}}
            ${subsection.name}
{{if (subsection.file)}}
            </a>
{{/if}}
            <strong>${subsection.subtitle}</strong>
            </li>

    {{/each}}
    </ul>
</fieldset>
{{/each}}
</div>