<div class="klearMatrixDashboard">

<h1 class="ui-state-active  ui-corner-all">${title}</h1>
<div>
{{each(idx,section) sections}}
<fieldset class="ui-widget-content ui-corner-all legacy" data-meta="${section.meta}">
<legend class="ui-state-active  ui-corner-all">${section.name}</legend>
    <ul>
        {{each(idx2,subsection) section.subsects}}
        {{if (subsection.subsects && subsection.subsects.length > 0)}}
        <li class="submenu">
            <h3>
                <span class="ui-silk inline ${subsection['class']}"></span>
                <span class="textnode">${subsection.name}</span>
            </h3>
            <div>
                <ul>
                    {{each(subidx,subsubsection) subsection.subsects}}
                    <li>
                        <strong>${subsubsection.subtitle}</strong>
                        {{if (subsubsection.file)}}
                        <a class="subsection" href="?" id="target-${subsubsection.file}" >
                            {{/if}}
                            {{if (subsubsection['class'])}}
                            <span class="ui-silk inline ${subsubsection['class']}"></span>
                            {{/if}}
                            ${subsubsection.name}
                            {{if (subsubsection.file)}}
                        </a>
                        {{/if}}
                    </li>
                    {{/each}}
                </ul>
            </div>
        </li>
        {{else}}
        <li>
            <strong>${subsection.subtitle}</strong>
            {{if (subsection.file)}}
            <a class="subsection" href="?" id="target-${subsection.file}" >
                {{/if}}
                {{if (subsection['class'])}}
                <span class="ui-silk inline ${subsection['class']}"></span>
                {{/if}}
                ${subsection.name}
                {{if (subsection.file)}}
            </a>
            {{/if}}
        </li>
        {{/if}}
    {{/each}}
    </ul>
</fieldset>
{{/each}}
</div>
</div>
