{{if (description)}}
    <p>${description}</p>
{{else}}
    <p><?php echo $this->translate('Do you want delete this record?'); ?></p>
{{/if}}

{{each(idx,row) values}}
    <p class="deleteable-item" data-id="${$item.getIndex(row,pk)}">
    {{each(colIdx,column) columns}}
        {{if (column['default'])}}
            ${name}:
            <strong>{{html $item.getStringIndexFromColumn(row,column)}}</strong>
        {{/if}}
    {{/each}}
        <em>(#${$item.getIndex(row,pk)})</em>
    </p>
{{/each}}
    <form class="klearMatrix_form autoclose-dialog">
    <span class="action autoClose ">
        <span>
            <input type="checkbox" name="autoclose" {{if (autoClose)}} checked="checked"{{/if}}/><?php echo $this->translate('Close automatically'); ?>
        </span>
    </span>
    </form>
