
{{each(idx,row) values}}
    {{if (description)}}
        <p>${description}</p>
    {{else}}
        <p><?php echo $this->translate('Do you want delete this record?'); ?></p>
    {{/if}}

    <p class="deleteable-item" data-id="${$item.getIndex(row,pk)}">
    {{each(colIdx,column) columns}}
        {{if (column['default'])}}
            ${name}:
            <strong>{{html $item.getStringIndexFromColumn(row,column)}}</strong>
        {{/if}}
    {{/each}}
        <em>(#${$item.getIndex(row,pk)})</em>
    </p>
{{/each}}