{{each(idx,row) values}}

<form class="klearMatrix_form" action="${saveAction}" data-id="${$item.getIndex(row,pk)}">
	<fieldset class="ui-widget-content ui-corner-all">
		<legend class="ui-widget-header ui-corner-all">${$item.getTitle(title,idx)}</legend>

	 	{{each(colIdx,column) columns}}
        <p class="ui-widget-content ui-corner-all">
            <label for="${id}${randIden}">${name}:</label>
            {{html $item.getEditDataForField(row[id],column)}}
            {{if (column.options)}}
                {{each column.options}}
                <a class="_fieldOption inherit option ${type} {{if (defaultOption)}}default{{/if}} ui-state-nojump"
                href=""
                data-${type}="${$item.getIndex($value,type)}"
                title="${$item.getTitle(title,idx,true)}">
                <span class="ui-silk inline ${icon}"></span>{{if (label) }}${$item.getTitle(title,idx,true)}{{/if}}</a>
                {{/each}}
            {{/if}}
		</p>
		{{/each}}
	</fieldset>

    <div class="generalOptionsToolbar ui-widget-content ui-corner-all">
        <a class="closeTab" href="" title="<?php echo $this->translate('Close'); ?>"><span class="ui-silk inline ui-silk-cross"></span><?php echo $this->translate('Close'); ?></a>
        <a class="action" href="" title="<?php echo $this->translate('Save'); ?>"><span class="ui-silk inline ui-silk-bullet-disk"></span><?php echo $this->translate('Save'); ?></a>
        <span class="action autoClose "><span><input type="checkbox" name="autoclose" /><?php echo $this->translate('Close automatically after save'); ?></span></span>

{{if (generalOptions.length>0) }}
    <br /><br />
{{each generalOptions}}

    <a class="_generalOption option ${type}" href="" data-${type}="${$item.getIndex($value,type)}" title="${$item.getTitle(title,idx,true)}" {{if (multiInstance)}} data-multiinstance='true'{{/if}}>
    <span class="ui-silk inline ${icon}"></span>
    ${$item.getTitle(title,idx,true)}
    </a>
{{/each}}
{{/if}}

    </div>

</form>
{{/each}}
