<div class="gChartsDashboard" id="dashboardBox_${randIden}">
	{{if (values.dashboard)}}
	<h1 id="dashboardTitle" class="ui-state-active  ui-corner-all">${values.dashboard.title}</h1>
	<div class="klearMatrixDashboard">
		{{each(idx,section) values.dashboard.sections}}
			<fieldset class="ui-widget-content ui-corner-all legacy">
				<legend class="ui-state-active  ui-corner-all">${section.name}</legend>
				 <ul>
        			{{each(idx2,subsection) section.subsects}}
						<li>
						{{if (subsection.file)}}
							<a class="subsection" href="?" id="target-${subsection.file}" >
						{{/if}}
						{{if (subsection['class'])}}
						            <span class="ui-silk inline ${subsection['class']}"></span>
						{{/if}}
						${subsection.name}
						{{if (subsection.file)}}
            				</a>
						{{/if}}
						<strong>${subsection.subtitle}</strong>
						</li>
        			{{/each}}
        		</ul>
			</fieldset>
		{{/each}}
	</div>
	{{/if}}
<div class="clear"></div>
<div class="gChartsDashboard" ui-state-active id="chartBox_${randIden}">
	{{if values.title}}
	<h1 id="chartsTitle" class="ui-state-active  ui-corner-all">${values.title}</h1>
	{{else}}
	<h1 id="chartsTitle" class="ui-state-active  ui-corner-all" style='display: none;'></h1>
	{{/if}}
<form>
	{{if values.chartGroups}}
		<!-- GRUPOS DE GRÁFICOS -->
		{{each(ids,group) values.chartGroups}}
			<fieldset  class="gGroup ui-widget-content ui-corner-all">
				<!-- TÍTULO DEL GRUPO -->
				{{if group.title}}
				<legend class="ui-state-active  ui-corner-all">${group.title}</legend>
				{{/if}}
				<!-- COMENTARIO DEL GRUPO -->
				{{if group.comment}}
					<div id="chart_${randIden}_${ids}_comment_div">
					</div>
				{{/if}}
				<!-- GRÁFICOS -->
				{{each(idx,chart) group.charts}}
					<!-- style="width: ${chart.options.width}px; min-width: ${chart.options.width}px;" -->
					{{if chart.options.width}}
					<fieldset  class="gChart ui-widget-content ui-corner-all">
					{{else}}
					<fieldset  class="gChart ui-widget-content ui-corner-all" style='min-width: 250px;'>
					{{/if}}
						<!-- TÍTULO DEL GRAFICO -->
						{{if chart.title}}
						<legend class="ui-state-active  ui-corner-all" style='max-width: ${chart.options.width}px;'>${chart.title}</legend>
						{{/if}}
						<!-- COMENTARIO DEL GRAFICO -->
						{{if chart.comment}}
							<div id="chart_${randIden}_${ids}_${idx}_comment_div" style='max-width: ${chart.options.width}px;'>
							</div>
						{{/if}}
						<!-- GRÁFICO PROPIAMENTE DICHO -->
						<!-- style="width: ${chart.options.width}px; min-width: ${chart.options.width}px;" -->
			    		<div id="chart_${randIden}_${ids}_${idx}_dashboard_div">
			    			<div id="chart_${randIden}_${ids}_${idx}_div"></div>
			    			<div id="chart_${randIden}_${ids}_${idx}_filter_div"></div>
			    		</div>
						<!-- LEYENDA DEL GRÁFICO -->
						{{if chart.legend}}
						<fieldset  class="ui-widget-content ui-corner-all" style='max-width: ${chart.options.width}px;'>
							<div id="chart_${randIden}_${ids}_${idx}_legend_div">
							</div>
						</fieldset>
						{{/if}}
					</fieldset>
				{{/each}}
			</fieldset>
		{{/each}}
	{{/if}}
</form>
</div>
</div>