{{if (info) }}

<div class="ui-widget-content ui-corner-all assistant">
<span class="
ui-silk
ui-silk-${info.icon}
fieldInfo-${info.type}
fieldInfo-position-${info.position}
"
data-title="${info.text}"
></span>{{if (info.label)}} ${info.label} {{/if}}
</div>
{{/if}}

<div class="ui-widget-content ui-corner-all klearMatrixFiltering">
<form class="klearMatrixFilteringForm {{if (typeof searchFields == 'undefined') }} not-loaded {{/if}} ">
{{if (preconfiguredFilters)}}
<p class="preconfiguredFilters">
<span class="ui-silk inline ui-silk-zoom-in"></span><?php echo $this->translate('Search shortcuts'); ?>: {{each(idx,filter) preconfiguredFilters}}
    <button class="preconfigureFilters" data-field="${filter.field}" data-value="${filter.value}">${filter.title}</button>
{{/each}}
</p>
{{/if}}
<p class="title"><span class="ui-silk inline ui-silk-zoom"></span><?php echo $this->translate('Filter fields'); ?></p>
{{if (searchFields) }}
    <span class="applyFilters" title="<?php echo $this->translate('Returns records that satisfy any of filters'); ?>">
        <?php echo $this->translate('Apply filters'); ?>
        <input type="checkbox" name="applyFilters"
        {{if (applySearchFilters) }}
            checked="checked"
        {{/if}}
    />
    </span>
{{/if}}
    <p class="filterItem">
    <span class="searchOption">
        <select name="searchOption">
            <option value="lt">menor</option>
            <option value="eq">igual</option>
            <option value="gt">mayor</option>
        </select>
    </span>
    <input type="text" class="term">
    <select name="searchField">

     {{each(idx,column) columns}}
         {{if ( (type != '_option') && (column.searchable) ) }}
            {{if (column.decorators)}}
                {{each(name, config) column.decorators}}

                    {{if (config._applyToListFiltering)}}
                        <option value="${column.id}" class="option command fieldDecorator ${column.type}"
                                data-field="${column.type}" data-fielddecorator="${name}" data-external="true" rel="${id}${randIden}"
                                {{each(key, val) config}}
                                    data-${key}="${val}"
                                {{/each}}
                        >${column.name}</option>
                    {{else}}
                        <option value="${column.id}" >${column.name}</option>
                    {{/if}}

                {{/each}}
            {{else}}
                <option value="${column.id}" >${column.name}</option>
            {{/if}}

         {{/if}}
     {{/each}}
    </select>
    <span class="ui-silk inline ui-silk-add addTerm"></span>
    <br />
    <span class="addToggle" title="<?php echo $this->translate('Returns records that satisfy any of filters'); ?>">
        <?php echo $this->translate('Add all filters'); ?>
        <input type="checkbox" name="addFilters"
        {{if (searchAddModifier) }}
            checked="checked"
        {{/if}}
        />
    </span>
    
    <p class="filteredFields">
    {{each(field,searchValues) searchFields}}

        {{if (($item.getColumnName(columns,field))) }}

        <span data-field="${field}" class="field">
            <strong>${$item.getColumnName(columns,field)}</strong>:

            {{each(_valIdx,_val) searchValues}}
                <span class="ui-widget-content ui-corner-all content" data-value="${_val}" data-op="${searchOps[field][_valIdx]}">
                {{if (searchPresetted)}}
                    <span class="ui-silk inline ui-silk-lock-go"></span>
                {{else}}
                    <span data-idx="${_valIdx}" class="ui-silk inline ui-silk-cancel removable"></span>
                {{/if}}
                    {{if (searchOps[field][_valIdx] == 'lt')}}
                        <strong>&lt;</strong>
                    {{/if}}
                    {{if (searchOps[field][_valIdx] == 'gt')}}
                        <strong>&gt;</strong>
                    {{/if}}

                    {{html $item.getValuesFromSelectColumn($item.getColumn(columns,field),_val)}}
                
                </span>
            {{/each}}
        </span>
        {{/if}}
    {{/each}}
    </p>
</form>
</div>

{{if ( (generalOptions.length>0) || $item.data.csv )  }}
    {{if (optionsPlacement == 'both' || optionsPlacement == 'top')}}
        <div class="generalOptionsToolbar{{if ($item.data.paginator)}} topToolbar{{/if}}">
        {{each generalOptions}}
            <a class="_generalOption option ${type}" href="" data-${type}="${$item.getIndex($value,type)}" title="${$item.getTitle(title,false)}" {{if (multiInstance)}} data-multiinstance='true'{{/if}}>
            <span class="ui-silk inline ${icon}"></span>
            {{if (label) }}
                ${$item.getTitle(title,false)}
            {{/if}}
            </a>
        {{/each}}

        {{if ($item.data.csv)}}
            <a class="_generalOption option csv" href="">
                <span class="ui-silk inline ui-silk-page-white-database"></span><?php echo $this->translate('Export to CSV'); ?>
            </a>
        {{/if}}


        </div>
    {{/if}}
{{/if}}

{{if ($item.data.paginator)}}
    {{if (paginator.pageCount>1)}}
        {{tmpl(paginator) $item.getPaginatorTemplate()}}
    {{/if}}
{{/if}}


<table class="kMatrix">
<caption class="ui-state-active ui-priority-primary">
${$item.getTitle(title,false)}
<span class="extraCaptionInfo">
<?php echo $this->translate("Total: "); ?><strong>${total}</strong> <?php echo $this->translate('Records'); ?>
{{if (paginator)}}
<?php echo ' | ' . $this->translate('Records per page:')?> <input value="${paginator.itemCountPerPage}" type="number" min="0" max="1000" />
{{/if}}
</span>
</caption>

<tr>
   {{each(idx,column) columns}}
            <th data-field="${column.id}" class="ui-widget-header{{if (type == '_option') ||  !(column.sortable)}} notSortable{{/if}}">
            <span class="title">${column.name}</span>
            {{if (column.sortable)}}
                {{if (column.order)}}
                    {{if (column.order=='asc')}}
                        <span class="order asc ui-icon ui-icon-circle-triangle-s"></span>
                    {{else}}
                        <span class="order desc ui-icon ui-icon-circle-triangle-n"></span>
                    {{/if}}
                {{else}}
                    {{if (type != '_option') }}
                    <span class="order ui-icon ui-icon-circle-triangle-s ui-state-disabled"></span>
                    {{/if}}
                {{/if}}
            {{/if}}
            </th>
   {{/each}}
</tr>

{{each(idx,row) values}}
<tr data-id="${$item.getIndex(row,pk)}">
   {{each columns}}
       {{if (type != '_option') }}
            <td class="ui-widget-content{{if ($value['default'])}} default{{/if}} {{if ($value.multilang)}} multilang{{/if}}">

                {{html $item.getIndexFromColumn(row,$value)}}

                {{if ($value.decorators)}}

                    {{each(idx, decorator) $value.decorators}}

                        {{if (decorator._applyToLists)}}

                            <a class="option command fieldDecorator ${$value.type}" data-field="${$value.type}" data-fielddecorator="${name}" data-external="true"
                            {{each(key, val) decorator}}
                                data-${key}="${val}"
                            {{/each}}
                            />
                        {{/if}}

                    {{/each}}
                {{/if}}

                {{if ($value.options)}}
                    {{each $value.options}}

                        {{if (
                            ($value.externalOption) &&
                            ( (showOnlyOnNotNull == false && showOnlyOnNull == false) ||
                              (showOnlyOnNotNull == true && row[id]) ||
                              (showOnlyOnNull == true && !row[id])
                             )
                        )}}
                            <a class="_fieldOption inherit option ${type} {{if (defaultOption)}}default{{/if}} ui-state-nojump"
                            href=""
                            data-${type}="${$item.getIndex($value,type)}"
                            title="${$item.getTitle(title,idx,true)}"
                            {{if ($value.externalOption === true)}}
                                data-externalid='${row[id]}'
								${$item.getExternalData($value)}
                            {{/if}}
                            >
                            <span class="ui-silk inline ${icon}"></span>{{if (label) }}${$item.getTitle(title,idx,true)}{{/if}}</a>
                         {{/if}}
                    {{/each}}
                {{/if}}

            </td>
        {{else}}
            <td class="ui-widget-content options">
            {{each fieldOptions}}
                {{html $item.parseParentOptionCustomizationOpen(row._optionCustomization, $value) }}
                <a class="_fieldOption option ${type} {{if (defaultOption)}}default{{/if}} ui-state-nojump" href="" data-${type}="${$item.getIndex($value,type)}" title="${$item.getTitle(title,idx,true)}"
                 {{if ($value.externalOption === true)}}
						data-externalid='${$item.getIndex(row,pk)}'
						${$item.getExternalData($value)}
				 {{/if}}
                >
                    <span class="ui-silk inline ${icon}"></span>
                    {{if (label) }}${$item.getTitle(title,idx,true)}{{/if}}
                </a>
                {{html $item.parseOptionCustomization(row._optionCustomization, $value) }}
                {{html $item.parseParentOptionCustomizationClose(row._optionCustomization, $value) }}
            {{/each}}
            </td>
        {{/if}}
    {{/each}}
</tr>
{{/each}}
</table>


<div class="bottomPaginator">
    {{if ($item.data.paginator)}}
        {{if (paginator.pageCount>1)}}
            {{tmpl(paginator) $item.getPaginatorTemplate()}}
        {{/if}}
    {{/if}}
</div>


{{if ((generalOptions.length > 0) || $item.data.csv )  }}
    {{if (optionsPlacement == 'both' || optionsPlacement == 'bottom')}}
        <div class="generalOptionsToolbar{{if ($item.data.paginator)}} bottomToolbar{{/if}}">
        {{each generalOptions}}
            <a class="_generalOption option ${type}" href="" data-${type}="${$item.getIndex($value,type)}" title="${$item.getTitle(title,false)}" {{if (multiInstance)}} data-multiinstance='true'{{/if}}>
            <span class="ui-silk inline ${icon}"></span>
            {{if (label) }}
                ${$item.getTitle(title,false)}
            {{/if}}
            </a>
        {{/each}}

        {{if ($item.data.csv)}}
            <a class="_generalOption option csv" href="">
                <span class="ui-silk inline ui-silk-page-white-database"></span><?php echo $this->translate('Export to CSV'); ?>
            </a>
        {{/if}}
        </div>
    {{/if}}
{{/if}}