<table class="kMatrix">
<caption class="ui-state-active ui-priority-primary">${title}</caption>

<tr>
   {{each(idx,column) columns}}
            <th class="ui-widget-header">${column.name}</td>
   {{/each}}
</tr>

{{each(idx,row) values}}
<tr data-id="${$item.getIndex(row,pk)}">
   {{each columns}}
   		{{if (type != '_option') }}
			<td class="ui-widget-content{{if ($value.default)}} default{{/if}}">{{html $item.getIndexFromColumn(row,$value)}}</td>
		{{else}}
			<td class="ui-widget-content options">
			{{each fieldOptions}}
				<a class="_fieldOption option ${type} {{if (defaultOption)}}default{{/if}}" href="" data-${type}="${$item.getIndex($value,type)}" title="${title}"><span class="ui-silk inline ${icon}"></span>{{if (label) }}${title}{{/if}}</a>
			{{/each}}
			</td>
		{{/if}}
	{{/each}}
</tr>
{{/each}}
</table>

{{if (generalOptions.length>0) }}
<div class="generalOptionsToolbar ui-widget-content ui-corner-all">
{{each generalOptions}}
	<a class="_generalOption option ${type}" href="" data-${type}="${$item.getIndex($value,type)}" title="${title}" {{if (multiInstance)}} data-multiinstance='true'{{/if}}>
	<span class="ui-silk inline ${icon}"></span>
	{{if (label) }}
		${title}
	{{/if}}
	</a>
{{/each}}
</div>
{{/if}}