<form class="klearMatrix_form" action="${saveAction}" data-type='new'>
    <fieldset class="ui-widget-content ui-corner-all">
		<legend class="ui-widget-header ui-corner-all">${title}</legend>

		{{each columns}}
	    <p class="ui-widget-content ui-corner-all">
            <label for="${id}${randIden}">${name}:</label>
	       {{tmpl($item.getDataForFieldTemplate('',$value)) $item.getTemplateForType($value)}}
        </p>
		{{/each}}
	</fieldset>
    <div class="generalOptionsToolbar ui-widget-content ui-corner-all">
        <a class="closeTab" href="" title="Cerrar"><span class="ui-silk inline ui-silk-cross"></span>Cerrar</a>
        <a class="action" href="" title="Guardar"><span class="ui-silk inline ui-silk-bullet-disk"></span>Guardar</a>
    </div>

</form>
