{{if (!_readonly)}}
    <input type="hidden" class="hiddenFile" name="${_elemName}" value="${_fieldValue.name}"
    {{if (_properties.required)}}required="" {{/if}}
    {{if (_dataConfig.allowed_extensions)}} data-extensions="${_dataConfig.allowed_extensions}"{{/if}}
    {{if (_dataConfig.uploadCommnad)}} data-upload="command" data-command="${_dataConfig.uploadCommnad}"{{/if}}
    id="${_elemIden}" />
{{/if}}

<span class="klearMatrix_file newFile" id="new_${_elemIden}"></span>

<span class="klearMatrix_file" id="current_${_elemIden}"
{{if (_fieldValue.name)}}
    data-filename="${_fieldValue.name}"
>
    {{if (!_dataConfig.options['hiddenName'])}}
        ${_fieldValue.name}
        {{if (_dataConfig.options['showFileSize'])}}
            <em>(${$item.formatSizeForFile(_fieldValue)})</em>
        {{/if}}
    {{/if}}


{{else}}
>
    <?php echo $this->translate('Not available'); ?>
{{/if}}

    {{each(idx,option) _dataConfig.options}}

        {{if ((!option.listController) && (!(option.onNull == 'hide' && !_fieldValue.name)))}}

        <a rel="${_elemIden}" href="#"
            {{if (option.title)}} title="${option.title}" {{/if}}
            class="option ${option['class']} ${option.type}"
             {{if (option.type)}}
                data-${option.type}="${option.target}"
             {{/if}}

             {{if (option.props)}}
                 {{each(propName,propValue) option.props}}
                    data-${propName}="${propValue}"
                 {{/each}}
             {{/if}}
            {{if (option.external)}}
                 data-external="true"
            {{/if}}
            >{{if (option.icon)}}<span class="ui-silk inline ${option.icon}"></span>{{/if}}</a>

            {{if (option.autoSaveWhenDone)}}
                <input
                    type="checkbox"
                    rel="${_elemName}_autosave"
                />

                <input
                    type="hidden"
                    id="${_elemIden}_autosave"
                    name="${_elemName}_autosave"
                    value="1"
                    class="checkboxn autosave"
                />

                ${$.translate("Auto-guardar al finalizar de subir.")}
            {{/if}}
        {{/if}}
    {{/each}}
</span>

