<span class="klearMatrix_file newFile" id="new_${_elemIden}"></span>
<span class="klearMatrix_file" id="current_${_elemIden}">

{{if (_fieldValue.name)}}
    ${_fieldValue.name}
{{else}}
    <?php echo $this->translate('Not available'); ?>
{{/if}}  
    
    {{each(idx,option) _dataConfig.options}}
    
        {{if (!(option.onNull == 'hide' && !_fieldValue.name))}}
        
            <a rel="${_elemIden}" href="#"
            {{if (option.title)}} title="${option.title}" {{/if}}
            class="option
             {{if (option.class)}}
                 ${option.class}
            {{/if}}
            {{if (option.type)}} 
                ${option.type}" data-${option.type}="${option.target}"
            {{/if}}
            {{if (option.external)}}
                 data-external="true"
            {{/if}}
            >
            {{if (option.icon)}}
                <span class="ui-silk inline ${option.icon}"></span>
            {{/if}}
            </a>
        {{/if}}
    {{/each}}

  


</span>
    
{{if (!_readonly)}}
    <input type="hidden" name="${_elemName}" value="${_fieldValue.name}"
    {{if (_properties.required)}}required="" {{/if}}
    {{if (_dataConfig.allowed_extensions)}} data-extensions="${_dataConfig.allowed_extensions}"{{/if}}
    {{if (_dataConfig.uploadCommnad)}} data-upload="command" data-command="${_dataConfig.uploadCommnad}"{{/if}}
    id="${_elemIden}" />
    
{{/if}}
