<span class="klearMatrix_file" id="current_${_elemIden}">
    ${_fieldValue.name}
    <a title="Descargar Fichero" href=""
    {{if (_dataConfig.downloadDialog)}}
        class="option dialog" data-dialog="${_dataConfig.downloadDialog}"
    {{/if}}
    >
        <span class="ui-icon ui-icon-disk inline"></span>
    </a>
</span>

    <span class="klearMatrix_file newFile" id="new_${_elemIden}"></span>

{{if (!_readonly)}} 
    <input type="hidden" name="${_elemName}" value="${_fieldValue.name}"  
    {{if (_properties.required)}}required="" {{/if}}
    {{if (_dataConfig.allowed_extensions)}} data-extensions="${_dataConfig.allowed_extensions}"{{/if}}
    {{if (_dataConfig.uploadCommnad)}} data-upload="command" data-command="${_dataConfig.uploadCommnad}"{{/if}}
    id="${_elemIden}" />
    <span class="qq-uploader" rel="${_elemIden}"></span>
{{/if}}
