{{if (_readonly)}}
    {{each(idx,dataValue) _dataConfig.values}}
        {{if ( (_fieldValue['relIndex']) && (_fieldValue['relIndex'][dataValue.key]) )}}
                 ${dataValue.item} / 
        {{/if}}
    {{/each}}

{{else}}

<select class="multiselect" multiple name="${_elemName}[]" id="${_elemIden}">
{{each(idx,dataValue) _dataConfig.values}}
        <option {{if ( (_fieldValue['relIndex']) && (_fieldValue['relIndex'][dataValue.key]) )}}
                 selected="selected"
            {{/if}}

        value="${dataValue.key}">${dataValue.item}</option>

{{/each}}
</select>
{{/if}}