{{if (_readonly)}}
    {{each(idx,dataValue) _dataConfig.values}}
        {{if ( (_fieldValue['relIndex']) && (_fieldValue['relIndex'][dataValue.key]) )}}
                 ${dataValue.item} /
        {{/if}}
    {{/each}}

{{else}}

<input type="hidden" name="${_elemName}[]" value="" />
<select
    class="multiselect"
    multiple
    name="${_elemName}[]"
    id="${_elemIden}"

    {{each(idx,attrValue) _dataConfig.attributes}}
        ${idx}="${attrValue}"
    {{/each}}
>
{{each(idx,dataValue) _dataConfig.values}}
        <option {{if ( (_fieldValue['relIndex']) && (_fieldValue['relIndex'][dataValue.key]) )}}
                 selected="selected"
            {{/if}}

        value="${dataValue.key}">${dataValue.item}</option>

{{/each}}
</select>
{{/if}}