{{if (_readonly)}}
    {{html _fieldValue}}
{{else}}
    <input type="text" class="auto" name="${_elemName}"
        {{if (_properties.required)}}
            required=""
        {{/if}}

        {{if (_properties.placeholder)}}
            placeholder="${_properties.placeholder}"
        {{/if}}

        {{if (_properties.pattern)}}
            pattern="${_properties.pattern}"
        {{/if}}

        {{if (_dataConfig.plugin)}}
            data-plugin="${_dataConfig.plugin}"
        {{/if}}

        {{each(attribute, value) _dataConfig.settings}}
            data-setting-${$item.dataParser(attribute, value)}="${value}"
        {{/each}}

        {{each(idx, attrValue) _dataConfig.attributes}}
            ${idx}="${attrValue}"
        {{/each}}

        id="${_elemIden}"
        value="${_fieldValue}"
    />

    {{if _dataConfig.settings.preconfiguredValues}}
        {{each(idx, value) _dataConfig.settings.preconfiguredValues}}
            <a class="spinnerPreconfiguredValues tooltip ui-button ui-widget ui-state-default ui-corner-all ui-button-text-only" data-value="${value}" data-field="${_elemName}" role="button" aria-disabled="false">
            <span class="ui-button-text">${value}</span>
            </a>
        {{/each}}
    {{/if}}
{{/if}}