<input type="text" class="number" name="${_elemName}" 
{{if (_properties.required)}}required="" {{/if}}  
{{if (_properties.placeholder)}}placeholder="${_properties.placeholder}" {{/if}} 
{{if (_properties.pattern)}}pattern="${_properties.pattern}" {{/if}}
{{if (_dataConfig.plugin)}}  data-plugin="${_dataConfig.plugin}" {{/if}}
{{each(idx,attrValue) _dataConfig.attributes}}
    ${idx}="${attrValue}"
{{/each}}
id="${_elemIden}" value="${_fieldValue}"{{if (_readonly)}} disabled="disabled"{{/if}} />