{{if (_readonly)}}
    {{each(idx,dataValue) _dataConfig.values}}
        {{if (_fieldValue && dataValue.key == _fieldValue)}}
            {{html dataValue.item }}
            <input type="hidden" name="${_elemName}" value="${_fieldValue}"
             {{if (_dataConfig.visualFilter)}}class="visualFilter"{{/if}}
             {{if (_dataConfig.visualFilter && _dataConfig.visualFilter.show[dataValue.key]) }}
                data-show="
                {{each(idxField,showField) _dataConfig.visualFilter.show[dataValue.key]}}
                    {{if (idxField != '__className')}}
                        ${showField},
                    {{/if}}
                {{/each}}"
            {{/if}}
            {{if (_dataConfig.visualFilter && _dataConfig.visualFilter.hide[dataValue.key]) }}
                data-hide="
                {{each(idxField,hideField) _dataConfig.visualFilter.hide[dataValue.key]}}
                    {{if (idxField != '__className')}}
                        ${hideField},
                    {{/if}}
                {{/each}}"
            {{/if}}
            />
        {{/if}}
    {{/each}}

{{else}}

    <ul
        class="radio"
        id="${_elemIden}"
        {{if (_dataConfig.visualFilter)}}
            class="visualFilter"
        {{/if}}
        {{if (_properties.required)}}
            required=""
        {{/if}}
    >

    {{each(idx,dataValue) _dataConfig.values}}
        <li>

            <input type="radio"
                id="${_elemIden}_${idx}"
                name="${_elemName}"

                {{if (_fieldValue && dataValue.key == _fieldValue)}}
                    checked="checked"
                {{/if}}
                {{if (dataValue.key != '__null__')}}
                    value="${dataValue.key}"
                {{else}}
                    value="__NULL__"
                {{/if}}

                {{if (_dataConfig.visualFilter && _dataConfig.visualFilter.show[dataValue.key]) }}
                    data-show="{{each(idxField,showField) _dataConfig.visualFilter.show[dataValue.key]}}
                    {{if (idxField != '__className')}}
                        ${showField},
                    {{/if}}
                    {{/each}}"
                {{/if}}
                {{if (_dataConfig.visualFilter && _dataConfig.visualFilter.hide[dataValue.key]) }}
                    data-hide="{{each(idxField,hideField) _dataConfig.visualFilter.hide[dataValue.key]}}
                        {{if (idxField != '__className')}}
                            ${hideField},
                        {{/if}}
                    {{/each}}"
                {{/if}}
            >
            <label for="${_elemIden}_${idx}">${dataValue.item}</label>
        </li>
    {{/each}}
    </ul>
{{/if}}