{{if (_readonly)}}
    {{each(idx,dataValue) _dataConfig.values}}
        {{if (_fieldValue && dataValue.key == _fieldValue)}}
            {{html dataValue.item }}
            <input type="hidden" name="${_elemName}" value="${_fieldValue}"
             {{if (_dataConfig.visualFilter)}}class="visualFilter"{{/if}}
             {{if (_dataConfig.visualFilter && _dataConfig.visualFilter.show[dataValue.key]) }}
                data-show="
                {{each(idxField,showField) _dataConfig.visualFilter.show[dataValue.key]}}
                    {{if (idxField != '__className')}}
                        ${showField},
                    {{/if}}
                {{/each}}"
            {{/if}}
            {{if (_dataConfig.visualFilter && _dataConfig.visualFilter.hide[dataValue.key]) }}
                data-hide="
                {{each(idxField,hideField) _dataConfig.visualFilter.hide[dataValue.key]}}
                    {{if (idxField != '__className')}}
                        ${hideField},
                    {{/if}}
                {{/each}}"
            {{/if}}
            />
        {{/if}}
    {{/each}}

{{else}}

<select
    data-preload="${_fieldValue}"
    name="${_elemName}"
    id="${_elemIden}"
{{if (_dataConfig.visualFilter)}}
    class="visualFilter"
{{/if}}
{{if (_decorators)}}
    data-decorator="true"
{{/if}}

{{if (_properties.required)}}
    required=""
{{/if}}

{{each(idx,attrValue) _dataConfig.attributes}}
    ${idx}="${attrValue}"
{{/each}}

>

{{each(idx,dataValue) _dataConfig.values}}
    <option{{if (_fieldValue && dataValue.key == _fieldValue)}} selected="selected"{{/if}}

    {{if (dataValue.data)}}
        {{each(extraDataLabel, extraDataVal) dataValue.data}}
            data-${extraDataLabel}="${extraDataVal}"
        {{/each}}
    {{/if}}
    
    
    {{if (dataValue.key != '__null__')}}
        value="${dataValue.key}"
    {{else}}
        value="__NULL__"
    {{/if}}
    {{if (_dataConfig.visualFilter && _dataConfig.visualFilter.show[dataValue.key]) }}
        data-show="{{each(idxField,showField) _dataConfig.visualFilter.show[dataValue.key]}}
        {{if (idxField != '__className')}}
            ${showField},
        {{/if}}
        {{/each}}"
    {{/if}}
    {{if (_dataConfig.visualFilter && _dataConfig.visualFilter.hide[dataValue.key]) }}
        data-hide="{{each(idxField,hideField) _dataConfig.visualFilter.hide[dataValue.key]}}
            {{if (idxField != '__className')}}
                ${hideField},
            {{/if}}
        {{/each}}"
    {{/if}}
    >${dataValue.item}</option>
{{/each}}
</select>
{{/if}}