{{if (_readonly)}}
    {{html _dataConfig.values[_fieldValue]}}
    <input type="hidden" name="${_elemName}" value="${_fieldValue}" />
{{else}}
<select name="${_elemName}" id="${_elemIden}" {{if (_dataConfig.visualFilter)}}class="visualFilter"{{/if}}>
{{each(idx,dataValue) _dataConfig.values}}
    {{if (idx != '__className')}}
        <option{{if (_fieldValue && idx == _fieldValue)}} selected="selected"{{/if}}
        
        {{if (idx != '__null__') }} value="${idx}" {{/if}}
        {{if (_dataConfig.visualFilter && _dataConfig.visualFilter.show[idx]) }}
            data-show="{{each(idxField,showField) _dataConfig.visualFilter.show[idx]}}
            {{if (idxField != '__className')}}
                ${showField},
            {{/if}}
            {{/each}}"
        {{/if}}
        {{if (_dataConfig.visualFilter && _dataConfig.visualFilter.hide[idx]) }}
            data-hide="{{each(idxField,hideField) _dataConfig.visualFilter.hide[idx]}} 
                {{if (idxField != '__className')}}
                    ${hideField},
                {{/if}}
            {{/each}}"
        {{/if}}
        >${dataValue}</option>
    {{/if}}
{{/each}}
</select>
{{/if}}