{{if (_readonly)}}
    {{html _dataConfig.values[_fieldValue]}}
    <input type="hidden" name="${_elemName}" value="${_fieldValue}" />
{{else}}
<select name="${_elemName}" id="${_elemIden}" {{if (_dataConfig.visualFilter)}}class="visualFilter"{{/if}}>
{{each(idx,dataValue) _dataConfig.values}}
    <option{{if (_fieldValue && dataValue.key == _fieldValue)}} selected="selected"{{/if}}

    {{if (dataValue.key != '__null__') }} value="${dataValue.key}" {{/if}}
    {{if (_dataConfig.visualFilter && _dataConfig.visualFilter.show[dataValue.key]) }}
        data-show="{{each(idxField,showField) _dataConfig.visualFilter.show[dataValue.key]}}
        {{if (idxField != '__className')}}
            ${showField},
        {{/if}}
        {{/each}}"
    {{/if}}
    {{if (_dataConfig.visualFilter && _dataConfig.visualFilter.hide[dataValue.key]) }}
        data-hide="{{each(idxField,hideField) _dataConfig.visualFilter.hide[dataValue.key]}}
            {{if (idxField != '__className')}}
                ${hideField},
            {{/if}}
        {{/each}}"
    {{/if}}
    >${dataValue.item}</option>
{{/each}}
</select>
{{/if}}