{{if (_readonly)}}
    {{html _fieldValue}}
{{else}}
    <textarea
        id="${_elemIden}"
        name="${_elemName}"
        class="auto"

        {{if (_properties.required)}}
            required=""
        {{/if}}

        {{if (_dataConfig.plugin)}}
            data-plugin="${_dataConfig.plugin}"
        {{/if}}

        {{if (_readonly)}}
            disabled="disabled"
        {{/if}}

        {{if (_multilang)}}
            data-multilang="${_locale}"
        {{/if}}

        {{each(attribute, value) _dataConfig.settings}}
            data-setting-${$item.dataParser(attribute, value)}="${value}"
        {{/each}}

        {{each(idx,attrValue) _dataConfig.attributes}}
            ${idx}="${attrValue}"
        {{/each}}

        >${_fieldValue}</textarea>
{{/if}}