<input
    type="text"
    id="${_elemIden}"
    name="${_elemName}"
    class="auto"
    value="${_fieldValue}"

    {{if (_properties.required)}}
        required=""
    {{/if}}

    {{if (_readonly)}}
        disabled="disabled"
    {{/if}}

    {{if (_properties.placeholder)}}
        placeholder="${_properties.placeholder}"
    {{/if}}

    {{if (_properties.pattern)}}
        pattern="${_properties.pattern}"
    {{/if}}

    {{if (_dataConfig.plugin)}}
        data-plugin="${_dataConfig.plugin}"
    {{/if}}

    {{each(attribute, value) _dataConfig.settings}}
        data-setting-${$item.dataParser(attribute, value)}="${value}"
    {{/each}}

    {{each(idx,attrValue) _dataConfig.attributes}}
        ${idx}="${attrValue}"
    {{/each}}
/>
